import type { Gender, PetCategory, PetSize, Species } from "@prisma/client";

export interface SeedPet {
  id: string;
  category: PetCategory;
  species: Species;
  size?: PetSize;
  gender: Gender;
  name?: string;
  breed?: string;
  color?: string;
  age?: number;
  region?: string;
  description: string;
  photos: string[];
  contactName?: string;
  contactPhone?: string;
}

export const SEED_PETS: SeedPet[] = [
  {
    id: "seed-reg-golden",
    category: "REGISTERED",
    species: "DOG",
    size: "LARGE",
    gender: "MALE",
    name: "大黄",
    breed: "金毛寻回犬",
    color: "金色",
    age: 3,
    region: "上海·浦东",
    description:
      "性格温顺的金毛寻回犬，一身金黄色长毛，耳朵柔软、尾巴蓬松，已绝育、疫苗齐全，见人就摇尾巴。",
    photos: ["/seed/dog-golden-retriever.jpg"],
    contactName: "张女士",
    contactPhone: "138-0000-0001",
  },
  {
    id: "seed-reg-corgi",
    category: "REGISTERED",
    species: "DOG",
    size: "SMALL",
    gender: "FEMALE",
    name: "短腿",
    breed: "威尔士柯基",
    color: "黄白色",
    age: 2,
    region: "北京·朝阳",
    description:
      "活泼的威尔士柯基犬，黄白双色短毛、短腿大耳朵，爱站立卖萌，背部黄褐色和胸口白毛非常明显。",
    photos: ["/seed/dog-corgi.jpg"],
    contactName: "李先生",
    contactPhone: "138-0000-0002",
  },
  {
    id: "seed-reg-husky",
    category: "REGISTERED",
    species: "DOG",
    size: "MEDIUM",
    gender: "MALE",
    name: "二哈",
    breed: "西伯利亚哈士奇",
    color: "红棕白色",
    age: 4,
    region: "深圳·南山",
    description:
      "少见的红棕白色西伯利亚哈士奇，脸部白色面罩清晰，双色眼，精力旺盛，红棕背毛和白色胸毛对比强烈。",
    photos: ["/seed/dog-husky.jpg"],
    contactName: "王女士",
    contactPhone: "138-0000-0003",
  },
  {
    id: "seed-reg-orange",
    category: "REGISTERED",
    species: "CAT",
    size: "SMALL",
    gender: "MALE",
    name: "橘座",
    breed: "中华田园猫(橘猫)",
    color: "橘白色",
    age: 2,
    region: "上海·徐汇",
    description:
      "橘白色中华田园猫，身上有橘色虎斑纹和白色胸口，绿眼睛，体型微胖亲人，毛色温暖醒目。",
    photos: ["/seed/cat-orange-tabby.jpg"],
    contactName: "陈先生",
    contactPhone: "138-0000-0004",
  },
  {
    id: "seed-reg-british",
    category: "REGISTERED",
    species: "CAT",
    size: "SMALL",
    gender: "FEMALE",
    name: "蓝妹",
    breed: "英国短毛猫",
    color: "蓝灰色",
    age: 1,
    region: "广州·天河",
    description:
      "蓝灰色英国短毛猫，圆脸、短密绒毛和铜色眼睛很典型，性格安静，喜欢趴在楼梯上看人。",
    photos: ["/seed/cat-british-shorthair.jpg"],
    contactName: "赵女士",
    contactPhone: "138-0000-0005",
  },
  {
    id: "seed-reg-tuxedo",
    category: "REGISTERED",
    species: "CAT",
    size: "SMALL",
    gender: "MALE",
    name: "奶牛",
    breed: "中华田园猫(奶牛)",
    color: "黑白色",
    age: 3,
    region: "杭州·西湖",
    description:
      "黑白配色的中华田园奶牛猫，黑色背部配白色胸口和白爪，像穿燕尾服，活泼粘人、辨识度高。",
    photos: ["/seed/cat-tuxedo.jpg"],
    contactName: "孙先生",
    contactPhone: "138-0000-0006",
  },
  {
    id: "seed-reg-rabbit",
    category: "REGISTERED",
    species: "OTHER",
    size: "SMALL",
    gender: "FEMALE",
    name: "团子",
    breed: "荷兰垂耳兔",
    color: "棕白花色",
    age: 1,
    region: "成都·武侯",
    description:
      "棕白花色荷兰垂耳兔，耳朵自然下垂，脸颊和身体有棕色斑块，爱吃蔬菜叶，毛茸茸的兔子特征明显。",
    photos: ["/seed/rabbit-lop.jpg"],
    contactName: "周女士",
    contactPhone: "138-0000-0007",
  },
  {
    id: "seed-lost-bichon",
    category: "LOST",
    species: "DOG",
    size: "SMALL",
    gender: "MALE",
    name: "雪球",
    breed: "比熊犬",
    color: "白色",
    age: 5,
    region: "北京·海淀",
    description:
      "白色卷毛比熊犬在小区附近走失，圆脸黑眼睛，佩戴橙色圆形名牌项圈，白色蓬松卷毛非常醒目，见到请联系。",
    photos: ["/seed/dog-bichon.jpg"],
    contactName: "刘先生",
    contactPhone: "138-0000-0008",
  },
  {
    id: "seed-lost-shiba",
    category: "LOST",
    species: "DOG",
    size: "MEDIUM",
    gender: "MALE",
    name: "旺财",
    breed: "柴犬",
    color: "赤黄色",
    age: 3,
    region: "南京·鼓楼",
    description:
      "赤黄色柴犬散步时挣脱走失，尖耳卷尾，白色腹部，佩戴黑色胸背带，性格机警，赤黄短毛和柴犬脸型明显。",
    photos: ["/seed/dog-shiba-inu.jpg"],
    contactName: "吴女士",
    contactPhone: "138-0000-0009",
  },
  {
    id: "seed-lost-tabby",
    category: "LOST",
    species: "CAT",
    size: "SMALL",
    gender: "FEMALE",
    name: "花卷",
    breed: "中华田园猫(虎斑)",
    color: "棕灰虎斑",
    age: 2,
    region: "西安·雁塔",
    description:
      "棕灰色虎斑长毛猫从阳台走失，背部有深色条纹，尾巴蓬松，爱爬树，虎斑纹和长毛特征清楚。",
    photos: ["/seed/cat-tabby.jpg"],
    contactName: "郑先生",
    contactPhone: "138-0000-0010",
  },
  {
    id: "seed-found-brindle",
    category: "FOUND",
    species: "DOG",
    size: "MEDIUM",
    gender: "UNKNOWN",
    breed: "中华田园犬(混种)",
    color: "黑棕虎斑纹",
    region: "武汉·洪山",
    description:
      "在油菜花田边发现的中华田园犬混种，黑棕虎斑纹短毛，佩戴紫色项圈，亲人不怕生，正在寻找主人。",
    photos: ["/seed/dog-mixed-brindle.jpg"],
    contactName: "宠缘小站志愿者",
    contactPhone: "138-0000-0011",
  },
  {
    id: "seed-found-tortie",
    category: "FOUND",
    species: "CAT",
    size: "SMALL",
    gender: "UNKNOWN",
    breed: "中华田园猫(玳瑁)",
    color: "玳瑁色",
    region: "重庆·渝中",
    description:
      "街边发现的玳瑁色中华田园猫，黑黄相间花纹分布在脸部和身体，体型偏瘦但亲人，寻找主人。",
    photos: ["/seed/cat-tortoiseshell.jpg"],
    contactName: "宠缘小站志愿者",
    contactPhone: "138-0000-0012",
  },
  {
    id: "seed-found-kitten",
    category: "FOUND",
    species: "CAT",
    size: "SMALL",
    gender: "UNKNOWN",
    breed: "中华田园猫",
    color: "橘白色",
    region: "苏州·姑苏",
    description:
      "墙头发现的橘白色小奶猫，约三个月大，橘色头部配白色身体，健康活泼，寻找原主人或领养人。",
    photos: ["/seed/cat-kitten.jpg"],
    contactName: "宠缘小站志愿者",
    contactPhone: "138-0000-0013",
  },
  {
    id: "seed-adopt-lab",
    category: "ADOPTION",
    species: "DOG",
    size: "LARGE",
    gender: "MALE",
    name: "黑豆",
    breed: "拉布拉多寻回犬",
    color: "黑色",
    age: 1,
    region: "天津·南开",
    description:
      "一岁黑色拉布拉多寻回犬幼犬，黑色短毛油亮，体格结实，接受过基础服从训练，疫苗齐全，寻找有养狗经验的家庭。",
    photos: ["/seed/dog-labrador-black.jpg"],
    contactName: "何女士",
    contactPhone: "138-0000-0014",
  },
  {
    id: "seed-adopt-calico",
    category: "ADOPTION",
    species: "CAT",
    size: "SMALL",
    gender: "FEMALE",
    name: "花花",
    breed: "中华田园猫(三花)",
    color: "三花色",
    age: 2,
    region: "长沙·岳麓",
    description:
      "黑白橘三花中华田园猫，脸部和背部有清晰三色斑块，已绝育驱虫，性格独立，适合安静家庭。",
    photos: ["/seed/cat-calico.jpg"],
    contactName: "高先生",
    contactPhone: "138-0000-0015",
  },
  {
    id: "seed-adopt-hamster",
    category: "ADOPTION",
    species: "OTHER",
    size: "SMALL",
    gender: "FEMALE",
    name: "豆豆",
    breed: "金丝熊(叙利亚仓鼠)",
    color: "金棕色",
    age: 1,
    region: "郑州·金水",
    description:
      "金棕色金丝熊叙利亚仓鼠，毛色油亮，圆耳朵和短尾巴可爱，含笼子和跑轮一起赠送。",
    photos: ["/seed/hamster-golden.jpg"],
    contactName: "林女士",
    contactPhone: "138-0000-0016",
  },
];
